DECLARE 
    NUM NUMBER := &NUM;
    REM NUMBER := 0;
    TEMP NUMBER;
    C NUMBER :=0 ;

BEGIN 
TEMP :=NUM;
 WHILE  TEMP >0 LOOP
    REM := MOD(TEMP,10);
    C := C + REM*REM*REM;
    TEMP := TRUNC(TEMP/10);
 END LOOP;
 IF C = NUM THEN 
    DBMS_OUTPUT.PUT_LINE(NUM||' : NUMBER IS ARMSTRONG NUMBER ');
 ELSE 
    DBMS_OUTPUT.PUT_LINE(NUM||' : NUMBER IS NOT ARMSTRONG NUMBER');
 END IF ;
 

END;