DECLARE 
    NUM NUMBER := &NUM;
    REV NUMBER :=0;
    REM NUMBER;
    TEMP NUMBER;
BEGIN 
    TEMP := NUM;
    WHILE TEMP > 0 LOOP   
        REM := MOD(TEMP,10);
        REV := REV*10+REM;
        TEMP := TRUNC(TEMP/10);
    END LOOP;

    IF REV = NUM THEN 
        DBMS_OUTPUT.PUT_LINE('NUMBER IS PLANDROM NUMBER');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('NUMBERIS NOT PLANDROM NUMBER');
    END IF;
END;