-- WITHOUT OUT USING THIRD VARIABLE 

DECLARE 
    NUM1 NUMBER :=&NUM1;
    NUM2 NUMBER :=&NUM2; 

BEGIN 
    DBMS_OUTPUT.PUT_LINE('NUMBER 1 :'||NUM1);
    DBMS_OUTPUT.PUT_LINE('NUMBER 2 :'||NUM2);
    NUM1 := NUM1+NUM2;
    NUM2 := NUM1-NUM2;
    NUM1 := NUM1-NUM2;
    DBMS_OUTPUT.PUT_LINE('NUMBER 1 :'||NUM1);
    DBMS_OUTPUT.PUT_LINE('NUMBER 2 :'||NUM2);
END;

-- USING OF THIRD VARIABLE 


DECLARE 
    NUM1 NUMBER :=&NUM1;
    NUM2 NUMBER :=&NUM2;
    TEMP NUMBER; 

BEGIN 
    DBMS_OUTPUT.PUT_LINE('NUMBER 1 :'||NUM1);
    DBMS_OUTPUT.PUT_LINE('NUMBER 2 :'||NUM2);
    TEMP := NUM1;
    NUM1 := NUM2;
    NUM2:=TEMP;
    DBMS_OUTPUT.PUT_LINE('NUMBER 1 :'||NUM1);
    DBMS_OUTPUT.PUT_LINE('NUMBER 2 :'||NUM2);
END;