

CREATE TABLE TEST (
    ID INT  PRIMARY KEY,
    NAME VARCHAR(10),
    EMAIL VARCHAR(20) UNIQUE
);

-- INSER DATA IN TABLE 
INSERT INTO TEST (ID,NAME,EMAIL) VALUES(101,'HITESH','ABC123@GMAIL.COM');


-- MODIFY DATA IN TABLE 
UPDATE TABLE TEST SET NAME='TONY' WHERE NAME='HITESH';

-- SELECT DATA FORM TABLE 

SELECT * FROM TEST;